import { Component } from '@angular/core';

// Stub generated by `ng g c components/orders` - checkout redirects here after a successful order.
// `imports: []` is fine while the template uses no directives or other components.
@Component({
  selector: 'app-orders',
  imports: [],
  templateUrl: './orders.component.html',
  styleUrl: './orders.component.css',
})
export class OrdersComponent {}
