import { Component, inject } from '@angular/core';
import { OrdersStore } from '../../store/orders/orders.store';
import { MatCardModule } from '@angular/material/card';
import { CurrencyPipe, DatePipe } from '@angular/common';
import type { OrderStatus } from '../../core/models/order.model';

// Stub generated by `ng g c components/orders` - checkout redirects here after a successful order.
// `imports: []` is fine while the template uses no directives or other components.
@Component({
  selector: 'app-orders',
  imports: [MatCardModule, DatePipe, CurrencyPipe],
  templateUrl: './orders.component.html',
  styleUrl: './orders.component.css',
})
export class OrdersComponent {
  store = inject(OrdersStore);

  statusColor(status: OrderStatus): string {
    switch (status) {
      case 'SHIPPED':
        return '#1565C0';
      case 'DELIVERED':
        return '#2E7D32';
      case 'CANCELLED':
        return '#C62828';
      default:
        return '#F9A825';
    }
  }
}
