import { Component, inject, type OnInit } from '@angular/core';
import { OrdersStore } from '../../store/orders/orders.store';
import { MatCardModule } from '@angular/material/card';
import { CurrencyPipe, DatePipe } from '@angular/common';
import type { OrderStatus } from '../../core/models/order.model';
import { RouterLink } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { MatAnchor } from '@angular/material/button';
import { ConfirmationService } from '../../shared/services/confimation.service';

// Stub generated by `ng g c components/orders` - checkout redirects here after a successful order.
// `imports: []` is fine while the template uses no directives or other components.
@Component({
  selector: 'app-orders',
  imports: [MatCardModule, DatePipe, CurrencyPipe, RouterLink, MatIconModule, MatAnchor],
  templateUrl: './orders.component.html',
  styleUrl: './orders.component.css',
})
export class OrdersComponent implements OnInit {
  store = inject(OrdersStore);
  confirmationService = inject(ConfirmationService);

  // The store is providedIn: 'root', so it survives navigation - it will NOT refetch by itself
  // when you come back to this page. Kicking the load off here is what keeps the list fresh.
  ngOnInit(): void {
    // rxMethod with a void input is called with no arguments.
    this.store.loadMyOrders();
  }

  // `async` here buys you a flat, readable flow: ask, wait for the answer, then act.
  // The await suspends this method until the user clicks - nothing else in the app blocks.
  async handleCancellation(orderId: number) {
    const confirmation = await this.confirmationService.confirm(
      `Are you sure you want to cancel order #${orderId}?`,
      'The order will be called off and the items returned to stock. This cannot be undone.',
      'Cancel order',
    );

    // Guard clause: bail out early on "no". Cheaper to read than wrapping the rest in an if.
    if (!confirmation) {
      return;
    }

    this.store.cancelOrder(orderId);
  }

  statusColor(status: OrderStatus): string {
    switch (status) {
      case 'SHIPPED':
        return '#1565C0';
      case 'DELIVERED':
        return '#2E7D32';
      case 'CANCELLED':
        return '#C62828';
      default:
        return '#F9A825';
    }
  }
}
